import { Inter, Roboto_Slab } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import MountedProvider from "@/providers/mounted.provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const jost = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jost.variable}`}>
      <body className="adminui-app" suppressHydrationWarning={true}>
        <MountedProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
          </ThemeProvider>
        </MountedProvider>
      </body>
    </html>
  );
}
